language: python
services:
  - MySQL
  - PostgreSQL
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO="Django==1.4.3" DBENGINE=sqlite
  - DJANGO="Django==1.4.3" DBENGINE=mysql
  - DJANGO="Django==1.4.3" DBENGINE=pg
  - DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/ DBENGINE=mysql
  - DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/ DBENGINE=pg
  - DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/ DBENGINE=sqlite
install:
  - sh -c "if [ '$DBENGINE' = 'pg' ]; then pip install -q psycopg2; fi"
  - sh -c "if [ '$DBENGINE' = 'mysql' ]; then pip install -q MySQL-python; fi"
  - pip install -q $DJANGO
  - python setup.py -q install
script:
  cd demoproject && ./manage.py test concurrency

before_install:
  - sh -c "if [ '$DBENGINE' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS concurrency;' -U postgres; fi"
  - sh -c "if [ '$DBENGINE' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS concurrency;'; fi"

before_script:
  - sh -c "if [ '$DBENGINE' = 'pg' ]; then psql -c 'CREATE DATABASE concurrency;' -U postgres; fi"
  - sh -c "if [ '$DBENGINE' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS concurrency;'; fi"
